import './tools/variables.scss';
import './tools/mixins.scss';
import './index.scss';
import './intro/intro.scss';
import './profile/profile.scss';
import './contacts/contacts.scss'; 
import './skills/skills.scss';
import './education/education.scss';
import './experience/experience.scss';
import './software/software.scss'